apiVersion: v1
data:
  {{- (.Files.Glob "assets/**.py").AsConfig | nindent 2 }}
kind: ConfigMap
metadata:
  name: rook-ceph-export
  #labels:
    #  - include "rook-ceph-export.labels" . | nindent 4 
  namespace: "{{ .Release.Namespace }}"
