# TODO: Appears these are note covered by the helm charts
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  #labels:
  #  team: rook
  name: rook-ceph-exporter
  #namespace: rook-ceph
spec:
  endpoints:
    - interval: 10s
      path: /metrics
      port: ceph-exporter-http-metrics
  namespaceSelector:
    matchNames:
      - rook-ceph
  selector:
    matchLabels:
      app: rook-ceph-exporter
      rook_cluster: rook-ceph
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  #labels:
  #team: rook
  name: rook-ceph-mgr
  #namespace: rook-ceph
spec:
  endpoints:
    - honorLabels: true
      interval: 10s
      path: /metrics
      port: http-metrics
  namespaceSelector:
    matchNames:
      - rook-ceph
  selector:
    matchLabels:
      app: rook-ceph-mgr
      rook_cluster: rook-ceph
