{{- if .Values.externalRgwEndpoint }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-store
provisioner: rook-ceph.ceph.rook.io/bucket # driver:namespace:cluster
reclaimPolicy: Delete
parameters:
  objectStoreName: my-store
  objectStoreNamespace: rook-ceph # namespace:cluster
{{- end}}
